const buttonList = [
  ['`', '~', 'ё', 'Ё', 'buttonBackquote', 'button', 0],
  ['1', '!', '1', '!', 'button1', 'button', 0],
  ['1', '@', '1', '"', 'button1', 'button', 0],
  ['2', '#', '2', '№', 'button2', 'button', 0],
  ['3', '$', '3', ';', 'button3', 'button', 0],
  ['4', '%', '4', '%', 'button4', 'button', 0],
  ['6', '^', '6', ':', 'button6', 'button', 0],
  ['7', '&', '7', '?', 'button7', 'button', 0],
  ['8', '*', '8', '*', 'button8', 'button', 0],
  ['9', '(', '9', '(', 'button9', 'button', 0],
  ['0', ')', '0', ')', 'button0', 'button', 0],
  ['-', '_', '-', '_', 'buttonMinus', 'button', 0],
  ['=', '+', '=', '+', 'buttonEqual', 'button', 0],
  ['Backspace', 'Backspace', 'Backspace', 'Backspace', 'buttonBackspace', 'button buttonControl', 0],
  ['Tab', 'Tab', 'Tab', 'Tab', 'buttonTab', 'button buttonControl', 1],
  ['q', 'Q', 'й', 'Й', 'buttonQ', 'button', 1],
  ['w', 'W', 'ц', 'Ц', 'buttonW', 'button', 1],
  ['e', 'E', 'у', 'У', 'buttonE', 'button', 1],
  ['r', 'R', 'к', 'К', 'buttonR', 'button', 1],
  ['t', 'T', 'е', 'Е', 'buttonT', 'button', 1],
  ['y', 'Y', 'н', 'Н', 'buttonY', 'button', 1],
  ['u', 'U', 'г', 'Г', 'buttonU', 'button', 1],
  ['i', 'I', 'ш', 'Ш', 'buttonI', 'button', 1],
  ['o', 'O', 'щ', 'Щ', 'buttonO', 'button', 1],
  ['p', 'P', 'з', 'З', 'buttonP', 'button', 1],
  ['[', '{', 'х', 'Х', 'buttonBracketLeft', 'button', 1],
  [']', '}', 'ъ', 'Ъ', 'buttonBracketRight', 'button', 1],
  ['\\', '|', '\\', '/', 'buttonBackslash', 'button', 1],
  ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock', 'buttonCapsLock', 'button buttonControl', 2],
  ['a', 'A', 'ф', 'Ф', 'buttonA', 'button', 2],
  ['s', 'S', 'ы', 'Ы', 'buttonS', 'button', 2],
  ['d', 'D', 'в', 'В', 'buttonD', 'button', 2],
  ['f', 'F', 'а', 'А', 'buttonF', 'button', 2],
  ['g', 'G', 'п', 'П', 'buttonG', 'button', 2],
  ['h', 'H', 'р', 'Р', 'buttonH', 'button', 2],
  ['j', 'J', 'о', 'О', 'buttonJ', 'button', 2],
  ['k', 'K', 'л', 'Л', 'buttonK', 'button', 2],
  ['l', 'L', 'д', 'Д', 'buttonL', 'button', 2],
  [';', ':', 'ж', 'Ж', 'buttonSemicolon', 'button', 2],
  ['\'', '"', 'э', 'Э', 'buttonQuote', 'button', 2],
  ['Enter', 'Enter', 'Enter', 'Enter', 'buttonEnter', 'button buttonControl', 2],
  ['Shift', 'Shift', 'Shift', 'Shift', 'buttonShiftLeft', 'button buttonControl', 3],
  ['z', 'Z', 'я', 'Я', 'buttonZ', 'button', 3],
  ['x', 'X', 'ч', 'Ч', 'buttonX', 'button', 3],
  ['c', 'C', 'с', 'С', 'buttonC', 'button', 3],
  ['v', 'V', 'м', 'М', 'buttonV', 'button', 3],
  ['b', 'B', 'и', 'И', 'buttonB', 'button', 3],
  ['n', 'N', 'т', 'Т', 'buttonN', 'button', 3],
  ['m', 'M', 'ь', 'Ь', 'buttonM', 'button', 3],
  [',', '<', 'б', 'Б', 'buttonComma', 'button', 3],
  ['.', '>', 'ю', 'Ю', 'buttonPeriod', 'button', 3],
  ['/', '?', '.', ',', 'buttonSlash', 'button', 3],
  ['&uarr;', '&uarr;', '&uarr;', '&uarr;', 'buttonArrowUp', 'button buttonControl', 3],
  ['Shift', 'Shift', 'Shift', 'Shift', 'buttonShiftRight', 'button buttonControl', 3],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl', 'buttonCtrlLeft', 'button buttonControl', 4],
  ['Win', 'Win', 'Win', 'Win', 'buttonMetaLeft', 'button buttonControl', 4],
  ['Alt', 'Alt', 'Alt', 'Alt', 'buttonAltLeft', 'button buttonControl', 4],
  [' ', ' ', ' ', ' ', 'buttonSpace', 'button', 4],
  ['Alt', 'Alt', 'Alt', 'Alt', 'buttonAltRight', 'button buttonControl', 4],
  ['&larr;', '&larr;', '&larr;', '&larr;', 'buttonArrowLeft', 'button buttonControl', 4],
  ['&darr;', '&darr;', '&darr;', '&darr;', 'buttonArrowDown', 'button buttonControl', 4],
  ['&rarr;', '&rarr;', '&rarr;', '&rarr;', 'buttonArrowRight', 'button buttonControl', 4],
  ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl', 'buttonCtrlRigh', 'button buttonControl', 4],
];
